"""local error

Revision ID: 3281a77eec6f
Revises: 51f5ccfba190
Create Date: 2014-10-07 15:22:19.996237

"""

# revision identifiers, used by Alembic.
revision = '3281a77eec6f'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
